"""Generate model_meta.lua — the REGISTERED, model-level traits from OpenRouter
(benchmarks, input/output modalities, capabilities). These are properties of the
model family, identical whoever serves it, so they live in a persistent file the
host config reads at init — not in volatile runtime state. Provider-level
pricing/caching/limits flow live via the source -> EMA instead.

Run as a job (startup + periodically):
    python scripts/refresh_model_meta.py [--out model_meta.lua]
"""
from __future__ import annotations

import argparse
import asyncio
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from llm_router_host import LLMRouterHost          # noqa: E402
from sources.openrouter import OpenRouterSource    # noqa: E402


def _lua_quote(s: str) -> str:
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def _lua_value(v) -> str:
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, (int, float)):
        return repr(float(v))
    raise TypeError(f"unserializable trait value: {v!r}")


def _lua_table(meta: dict) -> str:
    lines = ["-- GENERATED by scripts/refresh_model_meta.py — do not edit by hand.",
             "-- Model-level traits from OpenRouter (benchmarks/modalities/capabilities).",
             "return {"]
    for fam in sorted(meta):
        traits = meta[fam]
        body = ", ".join(f"{k} = {_lua_value(traits[k])}" for k in sorted(traits))
        lines.append(f"  [{_lua_quote(fam)}] = {{ {body} }},")
    lines.append("}")
    return "\n".join(lines) + "\n"


async def generate(config_path: Path, out_path: Path) -> int:
    """Fetch OpenRouter and (re)write the registered model_meta file. Returns
    the number of families with traits. A throwaway host supplies the catalog's
    provider_model_id -> family map; model_meta itself does not depend on it."""
    host = LLMRouterHost(router_path=ROOT / "core" / "router.lua",
                         config_path=config_path)
    host.init()
    meta = await OpenRouterSource(host.catalog()).model_meta()
    out_path.write_text(_lua_table(meta))
    return len(meta)


async def main() -> None:
    ap = argparse.ArgumentParser(prog="refresh_model_meta.py")
    ap.add_argument("--config", type=Path, default=ROOT / "config.live.lua")
    ap.add_argument("--out", type=Path, default=ROOT / "model_meta.lua")
    args = ap.parse_args()
    n = await generate(args.config, args.out)
    print(f"wrote {args.out} ({n} families with OpenRouter traits)")


if __name__ == "__main__":
    asyncio.run(main())
